parameters:
  - name: BuildArtifactsLocation
    type: string
        
stages:
  - stage: Deploy
    jobs:
      - job: UploadServiceUtilites_Restart
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: steps/upload-tools.yml
            parameters: 
              BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}
