parameters:
  - name: BuildArtifactsLocation
    type: string
    
stages:
  - stage: Publish
    jobs:
      - job: APIService
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: steps/apiservice.yml
            parameters: 
              BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}

      - job: Orchestrator
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: steps/orchestrator.yml
            parameters: 
              BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}

      - job: RESTleragent
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: steps/restleragent.yml
            parameters: 
              BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}

      - job: AgentUtilities
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: steps/agent-utilities.yml
            parameters: 
              BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}

      - job: TestInfra
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: steps/test-infra.yml
            parameters: 
              BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}
