trigger:
  batch : true
  branches:
    include:
      - 'main'

parameters:
  - name: variable_group
    displayName: Variable Group
    default: production

  - name: BuildArtifactsLocation
    displayName: Build Artifacts Location?
    default: production
    values:
    - current
    - production

variables:
  - template: 'variables/version-variables.yml'
  - group: ${{ parameters.variable_group }}
  - name: versionNumber
    value: $(version.major).$(version.minor).$(version.revision)

stages:
  - template: stages/publish/publish.yml
    parameters: 
      BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}
