trigger:
  batch : true
  branches:
    include:
      - 'main'

variables:
  - template: 'variables/version-variables.yml'
  - name: versionNumber
    value: $(version.major).$(version.minor).$(version.revision)
  - name: imageTagWithBuildDate
    value: $(imageTag)-$(Build.BuildNumber)

stages:
  - template: stages/build/build.yml