trigger:
  batch : true
  branches:
    include:
      - '*'

variables:
  - template: 'variables/version-variables.yml'
  - name: versionNumber
    value: $(version.major).$(version.minor).$(version.revision)

parameters:
  - name: BuildArtifactsLocation
    displayName: Build Artifacts Location?
    default: current
    values:
    - current
    - production

stages:
  - template: stages/build/build.yml
