trigger:
  batch : true
  branches:
    include:
      - '*'

variables:
  - name: devRevision
    value: 1
  - name: version.major
    value: 0
  - name: version.minor
    value: 7
  - name: version.revision
    value: $[counter(variables['devRevision'], 1)]
  - name: versionNumber
    value: $(version.major).$(version.minor).$(version.revision)

stages:
  - template: stages/build/build.yml
