trigger:
  batch : true
  branches:
    include:
      - '*'

parameters:
  - name: variable_group
    displayName: Variable Group
    default: staging

  - name: RunBvt
    displayName: Run BVT?
    default: Yes
    values:
    - Yes
    - No

  - name: BuildArtifactsLocation
    displayName: Build Artifacts Location?
    default: production
    values:
    - current
    - production

variables:
  - template: 'variables/version-variables.yml'
  - group: ${{ parameters.variable_group }}
  - name: versionNumber
    value: $(version.major).$(version.minor).$(version.revision)

stages:
  - template: stages/build/build.yml
    parameters: 
      BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}
  - template: stages/publish/publish.yml
    parameters: 
      BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}
  - template: stages/deploy/deploy-infrastructure.yml  
  - template: stages/deploy/deploy.yml  
    parameters: 
      BuildArtifactsLocation: ${{ parameters.BuildArtifactsLocation }}
  - template: stages/test/test.yml
    parameters: 
      RunBvt: ${{ parameters.RunBvt }}
